version: '3.4'

services:
  vc-db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "${DOCKER_SQL_PORT:-1433}:1433"
    expose:  
      - 1433  
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=${DB_PASS}
    volumes:
      - db-volume:/var/opt/mssql   
    networks:
      - virto

  platform-web:
    image: ghcr.io/virtocommerce/platform:3.815.0
    ports:
      - "${DOCKER_PLATFORM_PORT:-8090}:80"
    environment:
     - VirtoCommerce:AllowInsecureHttp=true
     - ConnectionStrings:VirtoCommerce=Data Source=vc-db;Initial Catalog=VirtoCommerceLocal;Persist Security Info=True;User ID=sa;Password=${DB_PASS};MultipleActiveResultSets=False;Encrypt=false;
     - ConnectionStrings:RedisConnectionString=redis,password=${REDIS_PASS}
     - Assets:FileSystem:PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/assets/
     - Assets:FileSystem:RootPath=/opt/virtocommerce/platform/wwwroot/assets
     - Content:FileSystem:PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/cms-content/
     - Content:FileSystem:RootPath=/opt/virtocommerce/platform/wwwroot/cms-content     
     - Search:Provider=${SEARCH_PROVIDER}
     - Search:Scope=platformindex
     - Search:ElasticSearch:Server=http://elastic:9200
     - ASPNETCORE_HTTP_PORTS=80
     - ASPNETCORE_URLS=http://+:80;
    depends_on:
      - vc-db
      - elastic
      - redis
    entrypoint: ["/wait-for-it.sh", "vc-db:1433", "-t", "120", "--", "dotnet", "VirtoCommerce.Platform.Web.dll"]
    volumes:
      - ${MODULES_VOLUME}:/opt/virtocommerce/platform/modules
      - ${APP_DATA_MODULES}:/opt/virtocommerce/platform/app_data/modules
      - ${CMS_CONTENT_VOLUME}:/opt/virtocommerce/platform/wwwroot/cms-content
      - ${ASSETS_VOLUME}:/opt/virtocommerce/platform/wwwroot/assets      
    networks:
      - virto
    restart: unless-stopped

  storefront-web:
    image: ghcr.io/virtocommerce/storefront:6.40.0-master-0380cf97
    ports:
      - "${DOCKER_STOREFRONT_PORT:-8091}:80"
    environment:
     - VirtoCommerce:AllowInsecureHttp=true
     - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
     - ConnectionStrings:ContentConnectionString=provider=LocalStorage;rootPath=/volumes/cms-content/
     - VirtoCommerce:Endpoint:Url=${PLATFORM_ENDPOINT_URL:-http://localhost:8090}
     - VirtoCommerce:Endpoint:Password=${PLATFORM_ENDPOINT_PASSWORD:-store}
     - ASPNETCORE_HTTP_PORTS=80
     - ASPNETCORE_URLS=http://+:80;
    depends_on:
      - vc-db
      - elastic
      - redis
    entrypoint: ["dotnet", "VirtoCommerce.Storefront.dll"]
    volumes:
      - ${CMS_CONTENT_VOLUME}:/volumes/cms-content
    networks:
      - virto
    restart: unless-stopped

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - virto
 
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
        - "6379:6379"
    environment:
        - REDIS_REPLICATION_MODE=master  
    networks:
        - virto

volumes:
  db-volume:
    name: db-volume

networks:
  virto:
     external:
        name: nat
